import type { Metadata } from "next";
import localFont from "next/font/local";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ConfigProvider, ConfigProviderProps } from "antd";
import { NextIntlClientProvider } from "next-intl";
import Header from "./components/Header";
import { getLocale } from "next-intl/server";
import "./globals.css";
import Footer from "./components/footer/Footer";

const danaRegular = localFont({
  src: "../../public/fonts/DanaFaNum-Regular.woff2",
});
const danaMedium = localFont({
  src: "../../public/fonts/DanaFaNum-Medium.woff2",
  variable: "--font-dana-medium",
});
const danaBold = localFont({
  src: "../../public/fonts/DanaFaNum-Bold.woff2",
  variable: "--font-dana-bold",
});
const poppinsRegular = localFont({
  src: "../../public/fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
});
const poppinsMedium = localFont({
  src: "../../public/fonts/Poppins-Medium.ttf",
  variable: "--font-poppins-medium",
});
const poppinsBold = localFont({
  src: "../../public/fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const antdThemeConfigs: ConfigProviderProps["theme"] = {
    token: {
      fontFamily:
        locale === "fa"
          ? "var(--font-dana-regular)"
          : "var(--font-poppins-regular)",
    },
  };

  return (
    <html lang={locale} dir={locale === "fa" ? "rtl" : "ltr"}>
      <body
        className={`${
          locale === "fa" ? danaRegular.className : poppinsRegular.className
        } ${danaMedium.variable} ${danaBold.variable} ${
          poppinsMedium.variable
        } ${poppinsBold.variable} bg-bg-primary`}
      >
        <NextIntlClientProvider>
          <ConfigProvider
            theme={antdThemeConfigs}
            direction={locale === "fa" ? "rtl" : "ltr"}
          >
            <ReactQueryProvider>
              <Header />
              {children}
              <Footer />
              {/* <main>
                {children}
                </main>
                <Navigations /> */}
            </ReactQueryProvider>
          </ConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
