import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ConfigProvider, ConfigProviderProps } from "antd";
import Navigations from "./components/Navigations";

const danaRegular = localFont({
  src: "../../public/fonts/DanaFaNum-Regular.woff2",
});
const danaMedium = localFont({
  src: "../../public/fonts/DanaFaNum-Medium.woff2",
  variable: "--font-dana-medium",
});
const danaBold = localFont({
  src: "../../public/fonts/DanaFaNum-Bold.woff2",
  variable: "--font-dana-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const antdThemeConfigs: ConfigProviderProps["theme"] = {
  token: {
    fontFamily: "var(--font-dana-regular)",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${danaRegular.className} ${danaMedium.variable} ${danaBold.variable} @container dark:bg-black`}
      >
        <main>
          <ReactQueryProvider >
            <ConfigProvider theme={antdThemeConfigs} direction="rtl">{children}</ConfigProvider>
          </ReactQueryProvider>
        </main>
        <Navigations />
      </body>
    </html>
  );
}
